In [56]:
dicts = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
          {'a': 100, 'b': 200, 'c': 300, 'd': 400},
          {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000 }]
df = pd.DataFrame(dicts)
df
from IPython.display import display

display(df.iloc[:2])
display(df.iloc[1,2])
display(df.iloc[:,:])
display(df.sum(axis=0))
df.to_numpy()

np.full((2, 5, 7), [1,2,3,4,5,6,7])

     a    b    c    d
0    1    2    3    4
1  100  200  300  400

300

      a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

a    1101
b    2202
c    3303
d    4404
dtype: int64

array([[[1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7]],

       [[1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7]]])

In [5]:
#
# example of binary data not directly supported in Pandas
# but easily read by another module
#
import scipy.io
mat = scipy.io.loadmat('datasets/matlab.mat')
mat

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Tue Feb  2 14:21:02 2021',
 '__version__': '1.0',
 '__globals__': [],
 'storage': array([[0.00000000e+00],
        [3.60020368e-04],
        [7.26299303e-04],
        ...,
        [1.36616373e-05],
        [1.35810556e-05],
        [1.36134929e-05]]),
 'T1': array([[475.5],
        [475.5],
        [475.4],
        ...,
        [476.8],
        [476.8],
        [476.8]]),
 'time': array([[10256548.8],
        [10256549. ],
        [10256549.2],
        ...,
        [10273672.4],
        [10273672.6],
        [10273672.8]]),
 'value': array([[10256548.8       ],
        [10256550.09106825],
        [10256550.31226313],
        ...,
        [10273670.63541315],
        [10273672.1572869 ],
        [10273672.87393071]])}

In [7]:
#
# excel data
#
import pandas as pd
#
# simple file 
#
dog_food_orders = \
    pd.read_excel('datasets/dog_food_orders.xlsx', engine = 'openpyxl')
dog_food_orders

                  product  wholesale_price   msrp  qty_ordered  qty_shipped
0           skippys_dream             8.99  18.38          100          100
1           just_the_beef             4.99  10.43          200          195
2        potatos_and_lamb             5.19  11.43           50           50
3  turkey_and_cranberries             5.98  12.00           50           50
4            roasted_duck             9.59  17.48           15           15

In [1]:
#
# read html from website
# Page name: Wind power
# Author: Wikipedia contributors
# Publisher: Wikipedia, The Free Encyclopedia.
# Date of last revision: 9 May 2021 22:11 UTC
# Date retrieved: 12 May 2021 23:32 UTC
# Permanent link: https://en.wikipedia.org/w/index.php?title=Wind_power&oldid=1022329353
# Primary contributors: Revision history statistics
# Page Version ID: 1022329353
# Date retrieved: 7 February 2021 20:17 UTC
#
import pandas as pd
#
data_url = 'https://en.wikipedia.org/wiki/Wind_power'
data = pd.read_html(data_url)
data

[    0                                                  1
 0 NaN  This article may lack focus or may be about mo...,
                                                    0
 0                                Part of a series on
 1                                 Sustainable energy
 2  Energy conservation Building insulation Cogene...
 3  Renewable energy Biomass Carbon-neutral fuel G...
 4  Sustainable transport Bicycle Cycle rickshaw E...
 5                  Renewable energy portal  Category
 6  .mw-parser-output .navbar{display:inline;font-...,
                  Wind farm  Capacity (MW)        Country  Refs
 0          Gansu Wind Farm           7965          China  [21]
 1      Muppandal wind farm           1500          India  [22]
 2  Alta (Oak Creek-Mojave)           1320  United States  [23]
 3      Jaisalmer Wind Park           1064          India  [24],
     0                                                  1
 0 NaN  Graphs are temporarily unavailable due to tech...,
                                                     0   1   2   3   4
 0   Number of countries with wind capacities in th... NaN NaN NaN NaN
 1                                                2018 NaN NaN NaN NaN
 2                                                2017 NaN NaN NaN NaN
 3                                                2016 NaN NaN NaN NaN
 4                                                2015 NaN NaN NaN NaN
 5                                                2012 NaN NaN NaN NaN
 6                                                2011 NaN NaN NaN NaN
 7                                                2010 NaN NaN NaN NaN
 8                                                2009 NaN NaN NaN NaN
 9                                                2008 NaN NaN NaN NaN
 10                                               2006 NaN NaN NaN NaN
 11                                               2005 NaN NaN NaN NaN
 12                                               2004 NaN NaN NaN NaN
 13                                               1999 NaN NaN NaN NaN
 14                                               1997 NaN NaN NaN NaN
 15                                               1995 NaN NaN NaN NaN
 16                                               1986 NaN NaN NaN NaN
 17                                               2018 NaN NaN NaN NaN
 18                                               2016 NaN NaN NaN NaN
 19                                               2015 NaN NaN NaN NaN
 20                                               2013 NaN NaN NaN NaN
 21                                               2009 NaN NaN NaN NaN
 22                                               2008 NaN NaN NaN NaN
 23                                               2006 NaN NaN NaN NaN
 24                                               2002 NaN NaN NaN NaN
 25                                               2019 NaN NaN NaN NaN
 26                                               2014 NaN NaN NaN NaN,
        0   1   2   3   4
 0   2018 NaN NaN NaN NaN
 1   2017 NaN NaN NaN NaN
 2   2016 NaN NaN NaN NaN
 3   2015 NaN NaN NaN NaN
 4   2012 NaN NaN NaN NaN
 5   2011 NaN NaN NaN NaN
 6   2010 NaN NaN NaN NaN
 7   2009 NaN NaN NaN NaN
 8   2008 NaN NaN NaN NaN
 9   2006 NaN NaN NaN NaN
 10  2005 NaN NaN NaN NaN
 11  2004 NaN NaN NaN NaN
 12  1999 NaN NaN NaN NaN
 13  1997 NaN NaN NaN NaN
 14  1995 NaN NaN NaN NaN
 15  1986 NaN NaN NaN NaN,
       0   1   2   3   4
 0  2018 NaN NaN NaN NaN
 1  2016 NaN NaN NaN NaN
 2  2015 NaN NaN NaN NaN
 3  2013 NaN NaN NaN NaN
 4  2009 NaN NaN NaN NaN
 5  2008 NaN NaN NaN NaN
 6  2006 NaN NaN NaN NaN
 7  2002 NaN NaN NaN NaN,
       0   1   2   3   4
 0  2019 NaN NaN NaN NaN
 1  2014 NaN NaN NaN NaN,
                                 vteEnergy  \
 0                   Outline History Index
 1                    Fundamental concepts
 2                                   Types
 3                         Energy carriers
 4                          Primary energy
 5                Energy system components
 6                          Use and supply
 7                                   Misc.
 8  Category  Commons  Portal  WikiProject

                                          vteEnergy.1
 0                              Outline History Index
 1  Energy Units Conservation of energy Energetics...
 2  Kinetic Internal Thermal Potential Gravitation...
 3  Radiation Enthalpy Mechanical wave Sound wave ...
 4  Fossil fuel Coal Petroleum Natural gas Nuclear...
 5  Energy engineering Oil refinery Electric power...
 6  Energy consumption Energy storage World energy...
 7                    Jevons paradox Carbon footprint
 8             Category  Commons  Portal  WikiProject  ,
                                        vteWind power  \
 0                                         Wind power
 1                                         Wind farms
 2                                      Wind turbines
 3                                Wind power industry
 4                                      Manufacturers
 5                                           Concepts
 6  Wind power portal  Category  Commons  Addition...

                                      vteWind power.1  \
 0  High-altitude History By country Land vehicles...
 1  Community-owned Farms by country Offshore farm...
 2  Aerodynamics Airborne Crosswind kite Design Fl...
 3        Consulting companies Manufacturers Software
 4  Enercon GE Wind Energy including GE Offshore W...
 5  2020s in wind power research Betz's law Blade ...
 6  Wind power portal  Category  Commons  Addition...

                                      vteWind power.2
 0                                                NaN
 1                                                NaN
 2                                                NaN
 3                                                NaN
 4                                                NaN
 5                                                NaN
 6  Wind power portal  Category  Commons  Addition...  ,
                             vteWind power by country  \
 0  Overview Wind power industry Africa Egypt Ethi...
 1                                           Overview
 2                                             Africa
 3                                               Asia
 4                                             Europe
 5                                      North America
 6                                            Oceania
 7                                      South America
 8  Wind power portal  Renewable energy portal  En...

                           vteWind power by country.1
 0  Overview Wind power industry Africa Egypt Ethi...
 1                                Wind power industry
 2                 Egypt Ethiopia Ghana Kenya Morocco
 3  Afghanistan Armenia Bhutan China (Hong Kong) G...
 4  Albania Austria Belgium Belarus Bulgaria Croat...
 5             Canada Costa Rica Mexico United States
 6                              Australia New Zealand
 7  Argentina Brazil Chile Colombia Uruguay Venezuela
 8  Wind power portal  Renewable energy portal  En...  ,
                0                                                  1
 0       Overview                                Wind power industry
 1         Africa                 Egypt Ethiopia Ghana Kenya Morocco
 2           Asia  Afghanistan Armenia Bhutan China (Hong Kong) G...
 3         Europe  Albania Austria Belgium Belarus Bulgaria Croat...
 4  North America             Canada Costa Rica Mexico United States
 5        Oceania                              Australia New Zealand
 6  South America  Argentina Brazil Chile Colombia Uruguay Venezuela,
                               vteElectricity delivery  \
 0                                            Concepts
 1                                             Sources
 2                                       Non-renewable
 3                                           Renewable
 4                                          Generation
 5                       Transmission and distribution
 6                                       Failure modes
 7                                  Protective devices
 8                              Economics and policies
 9                           Statistics and production
 10  Categories Electric power distribution Electri...

                             vteElectricity delivery.1  \
 0   Automatic generation control Backfeeding Base ...
 1   Non-renewable Fossil fuel power station Coal N...
 2   Fossil fuel power station Coal Natural gas Pet...
 3   Biogas Biofuel Biomass Geothermal Hydro Marine...
 4   AC power Cogeneration Combined cycle Cooling t...
 5   Demand response Distributed generation Dynamic...
 6   Blackout (Rolling blackout) Brownout Black sta...
 7   Arc-fault circuit interrupter Circuit breaker ...
 8   Availability factor Capacity factor Carbon off...
 9   List of electricity sectors Electric energy co...
 10  Categories Electric power distribution Electri...

                             vteElectricity delivery.2
 0                                                 NaN
 1                                                 NaN
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 5                                                 NaN
 6                                                 NaN
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10  Categories Electric power distribution Electri...  ,
                0                                                  1
 0  Non-renewable  Fossil fuel power station Coal Natural gas Pet...
 1      Renewable  Biogas Biofuel Biomass Geothermal Hydro Marine...,
   vteApplication of wind energy  \
 0                    Wind power
 1            Vehicle propulsion
 2             Kite applications
 3                   Air current

                      vteApplication of wind energy.1
 0                             Wind turbine Wind mill
 1  Sailboat Sailing ship Power kite SkySails Iceb...
 2                            Kite Human-lifting kite
 3                                        Windcatcher  ,
   vteRenewable energy by country and territory  \
 0                                       Africa
 1                                         Asia
 2                                       Europe
 3                               European Union
 4                                        Other
 5                                North America
 6                                      Oceania
 7                                South America
 8  Category Portals:  Energy  Renewable energy

       vteRenewable energy by country and territory.1
 0  Democratic Republic of the Congo Egypt Ethiopi...
 1  Afghanistan Bangladesh Bhutan Brunei China Ind...
 2  European Union Austria Czech Republic Cyprus D...
 3  Austria Czech Republic Cyprus Denmark Finland ...
 4  Albania Armenia Belarus Iceland Kosovo Norway ...
 5    Canada Costa Rica Honduras Mexico United States
 6          Australia Cook Islands New Zealand Tuvalu
 7                    Argentina Brazil Chile Colombia
 8        Category Portals:  Energy  Renewable energy  ,
                 0                                                  1
 0  European Union  Austria Czech Republic Cyprus Denmark Finland ...
 1           Other  Albania Armenia Belarus Iceland Kosovo Norway ...,
                                  vteNatural resources  \
 0                                                 Air
 1                                 Pollution / quality
 2                                           Emissions
 3                                              Energy
 4                                                Land
 5                                                Life
 6                                               Water
 7                                    Types / location
 8                                             Aspects
 9                                             Related
 10  Commons enclosure global land tragedy of Econo...
 11                                           Resource
 12                                           Category

                                vteNatural resources.1
 0   Pollution / quality Ambient standards (USA) In...
 1   Ambient standards (USA) Index Indoor Law Clean...
 2                Airshed Trading Deforestation (REDD)
 3   Law Resources Fossil fuels (gas, Peak coal, Pe...
 4   Arable peak farmland Degradation Landscape cit...
 5   Biodiversity Bioprospecting Biosphere Bushfood...
 6   Types / location Aquifer storage and recovery ...
 7   Aquifer storage and recovery Drinking Fresh Gr...
 8   Desalination Floods Law Leaching Sanitation Co...
 9   Commons enclosure global land tragedy of Econo...
 10  Commons enclosure global land tragedy of Econo...
 11  Common-pool Conflict (perpetuation) Curse Depl...
 12                                           Category  ,
                      0                                                  1
 0  Pollution / quality  Ambient standards (USA) Index Indoor Law Clean...
 1            Emissions               Airshed Trading Deforestation (REDD),
                   0                                                  1
 0  Types / location  Aquifer storage and recovery Drinking Fresh Gr...
 1           Aspects  Desalination Floods Law Leaching Sanitation Co...,
                                                    0  \
 0  Commons enclosure global land tragedy of Econo...
 1                                           Resource

                                                    1
 0  Commons enclosure global land tragedy of Econo...
 1  Common-pool Conflict (perpetuation) Curse Depl...  ,
   Authority control                                Authority control.1
 0          National  France BnF data Germany Israel United States J...
 1             Other                                               NARA]

In [2]:
data[1]

                                                   0
0                                Part of a series on
1                                 Sustainable energy
2  Energy conservation Building insulation Cogene...
3  Renewable energy Biomass Carbon-neutral fuel G...
4  Sustainable transport Bicycle Cycle rickshaw E...
5                  Renewable energy portal  Category
6  .mw-parser-output .navbar{display:inline;font-...

In [ ]:
#
# normal csv file
#
import pandas as pd
#
pd.read_csv('datasets/bike_share.csv')

In [ ]:
#
# csv stored in a different character encoding
#
import pandas as pd
#
pd.read_csv('datasets/bike_share_UCS_2_LE_BOM.csv')

In [ ]:
#
# specify encoding to read file
#
import pandas as pd
#
pd.read_csv('datasets/bike_share_UCS_2_LE_BOM.csv', 
            encoding = 'utf_16_le')

In [ ]:
#
# specify encoding and a separator
#
pd.read_csv('datasets/bike_share_UCS_2_LE_BOM.tsv', 
            encoding = 'utf_16_le',
            sep = '\t')

In [ ]:
import pandas as pd
import sqlite3
#
# connect to bike_share.db -- will create if does not exist
#
conn = sqlite3.connect('datasets/bike_share.db')
c = conn.cursor()
#
# get data into a Pandas DataFrame
#
data = pd.read_csv('datasets/bike_share_UCS_2_LE_BOM.tsv', 
                   encoding = 'utf_16_le',
                   sep = '\t')
#
# this is how we execute SQL language commands
# here, we create a table with three columns
#
c.execute('CREATE TABLE IF NOT EXISTS RENTALS (Date, Hour, Qty)')
conn.commit()
#
# now that we have the table, we can put our data into it
#
data.to_sql("RENTALS", conn, if_exists = 'replace')

In [ ]:
#
# json data
#
import requests
#
US_counties_query = \
    requests.get('https://api.census.gov/data/2010/dec/sf1?get=NAME&for=county:*')
US_counties_query.text

In [ ]:
#
# decode the string into a list, then break down the list
#
import ast
US_counties_data = ast.literal_eval(US_counties_query.text)
[US_counties_data[i] for i in range(len(US_counties_data))]

In [ ]:
#
# convert json to Pandas
#
import pandas as pd
#
US_counties_data = pd.read_json(US_counties_query.text)
US_counties_data

In [ ]:
#
# we can get the same result using only .read_json()
#
URL = \
'https://api.census.gov/data/2010/dec/sf1?get=NAME&for=county:*'
US_counties_data = pd.read_json(URL).loc[1:, :]
US_counties_data.columns = ['County', 
                            'state_code', 
                            'county_code']
US_counties_data

In [ ]:
#
# read html from website
# Page name: Wind power
# Author: Wikipedia contributors
# Publisher: Wikipedia, The Free Encyclopedia.
# Date of last revision: 9 May 2021 22:11 UTC
# Date retrieved: 12 May 2021 23:32 UTC
# Permanent link: https://en.wikipedia.org/w/index.php?title=Wind_power&oldid=1022329353
# Primary contributors: Revision history statistics
# Page Version ID: 1022329353
# Date retrieved: 7 February 2021 20:17 UTC
#
import pandas as pd
#
data_url = 'https://en.wikipedia.org/wiki/Wind_power'
data = pd.read_html(data_url)
len(data)

In [ ]:
data[2]

In [ ]:
#
# access XML data
#
import pandas as pd
import pandas_read_xml as pdx
pdx.read_xml('https://data.cityofnewyork.us/api/views/825b-niea/rows.xml?accessType=DOWNLOAD',
             ['response', 'row', 'row'],
             root_is_rows = False)

In [ ]:
#
# a file with contents that aren't part of the data
#
import pandas as pd
#
sensor_data = pd.read_excel('datasets/sensor_data.xlsx',
                            usecols = [2, 3, 4, 5],
                            header = 3,
                            sheet_name = '20210117_0037',
                            engine = 'openpyxl')
sensor_data

In [ ]:
#
# store the cleaned sensor data to a new file in Excel format
#
sensor_data.to_excel('datasets/sensor_data_clean.xlsx', 
                     sheet_name = 'sensor_data',
                     index = None,
                     engine = 'openpyxl')

In [ ]:
#
# read sas data
#
# sample from http://www.principlesofeconometrics.com/sas.htm
#
import pandas as pd
#
data = pd.read_sas('datasets/airline.sas7bdat')
data.head()

In [ ]:
#
# read spss data
#
# example from http://calcnet.mth.cmich.edu/org/spss/prj_body_fat_data.htm
# requires optional dependency 'pyreadstat'; use pip or conda to install pyreadstat
#
import pandas as pd
data = pd.read_spss('datasets/bodyfat.sav')
data.head()

In [ ]:
#
# read stata data
#
# example from https://www.federalreserve.gov/econres/scfindex.htm
#
import pandas as pd
#
data = pd.read_stata('datasets/rscfp2019.dta')
print('data:\n', data.head(2))
data.to_stata('datasets/rscfp2019_write.dta', write_index = False)
data2 = pd.read_stata('datasets/rscfp2019_write.dta')
print('data2:\n', data2.head(2))
print('differences between rscfp2019 and rscfp2019_write:\n', 
      data.compare(data2))

In [ ]:
#
# work with hdf5 data
#
import pandas as pd
import numpy as np
#
time = np.arange(0, 100, 0.01)
values = np.sin(2 * np.pi * time / 17)
data = pd.DataFrame({'time': time, 'data': values})
#
data.to_hdf('store_data_h5.h5', 'table', append = True)
data_reread = pd.read_hdf('store_data_h5.h5', 'table', where = ['index > 9'])
data_reread.head()

In [ ]:
import pandas as pd
import sqlite3
tables = \
    pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name ASC", 
    sqlite3.connect('datasets/pet_stores.db'))
tables

In [ ]:
#
# use Pandas to make a copy of the database
#
import pandas as pd
import sqlite3
stores = pd.read_sql("SELECT * FROM Customers",
                     sqlite3.connect('datasets/pet_stores.db'))
invoices = pd.read_sql("SELECT * FROM Invoices",
                     sqlite3.connect('datasets/pet_stores.db'))
#
stores.to_sql("Customers", 
              sqlite3.connect('datasets/pet_stores_2.db'), 
              if_exists = 'replace',
              index = True)
invoices.to_sql("Invoices",
                sqlite3.connect('datasets/pet_stores_2.db'), 
                if_exists = 'replace',
                index = True)

In [ ]:
#
# read all the customers
#
customers = \
    pd.read_sql(
    'select Customer_Number, Company, City, State from Customers', 
    sqlite3.connect('datasets/pet_stores_2.db'))
customers

In [ ]:
#
# read the customers from TX
#
TX_customers = \
    pd.read_sql(
    "select Customer_Number, Company, City, State from Customers " + 
    "WHERE State = 'TX'", 
    sqlite3.connect('datasets/pet_stores_2.db'))
TX_customers

In [ ]:
customers.loc[customers['State'] == 'TX', :]

In [ ]:
#
# get the invoices table
#
invoices = pd.read_sql("select * from Invoices", 
                       sqlite3.connect('datasets/pet_stores_2.db'))
print(invoices.head(3), '\n', invoices.tail(3))

In [ ]:
#
# get new invoices from csv file
#
new_invoices = pd.read_csv('datasets/new_invoices.csv')
new_invoices

In [ ]:
#
# update the DataFrame index so it extends the index
#
new_invoices.index = list(range(invoices['index'].max() + 1, 
                                invoices['index'].max() + 
                                new_invoices.shape[0] + 1))
new_invoices

In [ ]:
#
# add the invoices to the table
#
new_invoices.to_sql("Invoices", 
                     sqlite3.connect('datasets/pet_stores_2.db'), 
                     if_exists = 'append',
                     index = True)

In [ ]:
invoices = pd.read_sql("select * from Invoices", 
                       sqlite3.connect('datasets/pet_stores_2.db'))
print(invoices.head(), '\n', invoices.tail())